### PR TITLE
Add battery level to xinput

### PR DESCRIPTION
**Pull request by Shadlock0133**
I've noticed #239 and decided to try implement it.

### CODE REVIEW

**Comment by Shadlock0133** [comment]
I've actually made the it first on the `master` branch, and it worked there. Before sending PR, I noticed that `buttplug-v6` branch was ahead, so I quickly rebased onto it, but forgot to test if to works 😅. Just tested, it looks like it doesn't detect my Xinput controller as a device now.

**Comment by qdot** [comment]
Oh interesting! Didn't expect device connection to break, but who knows what all this refactor has fucked up. >.> 

Anyways, yeah, it's fine that it's here, I *need* to get v6 done in like the next month or so anyways. If it worked in master and at least compiles in v6, I'll land to v6 then just test once I have the device creation stuff reassembled.

**Comment by Shadlock0133** [comment]
Actually, as I'm working again with v5, I've noticed it might have been my fault. To make it work with v6, I had to switch from
```rust
client.connect_in_process(None)
```
to
```rust
let in_process = ButtplugInProcessClientConnector::default();
client.connect(in_process)
```
since it doesn't have `connect_in_process`. And I just noticed `connect_in_process` adds all device managers for you. So probably not a bug in buttplug-v6, but my mistake. Sorry for the confusion.

**Comment by qdot** [comment]
connect_in_process in v6 is now util::in_process_client().

**Pull request merged**
