### PR TITLE
feat: Add support for Galaku one-engine devices

### PR DESCRIPTION
**Pull request by Ljzd-PRO**
Due to changes in the branch, the original pull request #621 has been closed.

### CODE REVIEW

**Comment by qdot** [comment]
There's no need to make new PRs for branch changes, you can just rebase in. I'll hopefully be bringing this in soon.

**Comment by qdot** [comment]
@blackspherefollower Can you check this out soon so we can bring it in?

**Comment by blackspherefollower** [comment]
Yeah, I've got some time free tomorrow.

**Comment by blackspherefollower** [comment]
My first thought is that this protocol should just be `galaku`: my suspicious is that the dual actuator models use the same encryption, so naming the protocol such that it implies it will only apply to single actuator devices is probably going to be misleading in the future.

**Comment by Ljzd-PRO** [comment]
The Galaku WeChat app categorizes products into electric shock, one-engine, and two-engine products. Each type of product generates communication data differently, but shared some functions and constants.

**Comment by blackspherefollower** [comment]
I'd love to know more about how you got here: there's quite a list of devices here but none are individually named.

I have to assume you either picked through the APK or the WeChat applet: what did you learn? A companion issue over on https://github.com/buttplugio/docs.buttplug.io/issues to document this would be good.

So far this implementation has worked for about half of the Galaku I've collected

**Comment by blackspherefollower** [comment]
> The Galaku WeChat app (source code) categorizes products into electric shock, one-engine, and two-engine products. Each type of product generates communication data differently, but shared some functions and constants.

Well that answers a couple of questions already.

Buttplug's device config should provide the context as to whether a device is 1 or 2 motor (and it would extend to shock capability if we supported that) - the protocol logic can then choose between the actual messages sent based on the device's capabilities.

**Comment by blackspherefollower** [comment]
> Each type of product generates communication data differently, but shared some functions and constants.

Is the battery reading logic the same? Is the encryption the same?

**Comment by blackspherefollower** [comment]
Tested:
* GK27 - Stroker vibe 👍 
* GK26 - Little Pea (panty vibe) 👍

**Comment by Ljzd-PRO** [comment]
> > Each type of product generates communication data differently, but shared some functions and constants.
> 
> Is the battery reading logic the same? Is the encryption the same?

It should be the same because only one command function for reading battery level was found.

**Comment by blackspherefollower** [comment]
Cool, so lets not worry about multi-actuator devices right now, but given that there's going to de enough overlap to be worth it, lets rename the protocol to just `galaku` and maybe run `cargo fmt -- --emit=files` for reformatting

**Comment by blackspherefollower** [comment]
@qdot I think we're good to go

**Pull request merged**
