### PR TITLE
Added ProtocolHandler for LovenseConnectService

### PR DESCRIPTION
**Pull request by SutekhVRC**
- Added ProtocolHandler impl.
- Changed the device config files to add ScalarCmd to Lovense Max.
- Suggested a few alternatives to the specification of Lovense Connect constriction.

- Ignore old commit for fixing Lovense Connect DOS (oops didnt meant to include it).

### CODE REVIEW

**Comment by SutekhVRC** [comment]
There are more detailed notes in the code comments!

**Comment by qdot** [comment]
Just got a few small comments:

You should rebase this on top of the dev branch, I already have the lovense connect service commit in.

Does this need to wait on the step count adjustment on the max? Just remembered that I saw you and @blackspherefollower discussing that.

Also, on the device config file, can you increment the minor version by one? I need to put that in as a rule for editting that file.

**Comment by SutekhVRC** [comment]
Just got a few small comments:
 
> You should rebase this on top of the dev branch, I already have the lovense connect service commit in.
> Omki!

> Does this need to wait on the step count adjustment on the max? Just remembered that I saw you and @blackspherefollower discussing that.
> Yes I will be changing the commit to use AirAuto only, as well as the step count to 3.

> Also, on the device config file, can you increment the minor version by one? I need to put that in as a rule for editting that file.
> Yes

**Comment by SutekhVRC** [comment]
Old

**Pull request closed without merging**
