### PR TITLE
Fix linux hidapi backend

### PR DESCRIPTION
**Pull request by SystemF0x**
This seems to fix an issue with Linux where the Lovense HID dongle isn't detected by Intiface on Linux.

**WARNING**
Due to an issue with cargo where the selective dependencies don't seem to work correctly you can only build with ``cargo +nightly -Z features=itarget build`` after applying this fix.

I don't know if this can be fixed in another way without breaking builds on the stable toolchain.
I am also only able to test this on Linux so I can't say for sure if this still works on Windows.

### CODE REVIEW

**Comment by qdot** [comment]
There's no way I can bring this in if it's gonna force nightly. I'll watch for package support and see if this can be built, but until then, I recommend getting a real bluetooth dongle. The Lovense one is a mess anyways.

**Comment by SystemF0x** [comment]
I will check if there is any way to do this without forcing nightly, when there is some way to force the hidraw backend inside the program instead of using the feature enabled in the dependency.

Hopefully the required feature to switch dependencies gets pushed into stable cargo at some point.

The reason I'm currently not using a bluetooth dongle is that the bluetooth system on linux seems to crash randomly when using a chromium based browser, but this isn't a buttplug related issue.

**Comment by SystemF0x** [comment]
I tested adding the feature directly to all platforms and it seems to work fine. 
Tested it on Linux and in a Windows VM.

**Comment by qdot** [comment]
Ok great, thanks for checking this! I'll run a couple of tests over here and then will bring this in for v5.1.1 or whatever is next.

**Comment by qdot** [comment]
Ok I had to rebase this for the 5.1.1 release, but it's now in dev, and should be pushed within the hour. Thanks for helping out with this, and please let me know if you run into anything else! I'm admittedly pretty lax on my linux testing. >.>

**Pull request closed without merging**
